# Generated by Django 4.2.2 on 2023-07-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
