# Generated by Django 4.2.2 on 2023-07-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
