# Generated by Django 4.2.2 on 2023-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
