# Generated by Django 4.2.2 on 2023-07-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0004_alter_employeedetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('annual', 'annual'), ('casual', 'casual'), ('sick', 'sick'), ('maternity', 'maternity'), ('paternity', 'paternity'), ('miscarriage', 'miscarriage'), ('special', 'special'), ('special_hajj', 'special_hajj'), ('other', 'other')], max_length=12)),
                ('allowed_days', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='total_remaining_leaves',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.ManyToManyField(related_name='leave_name', to='lms.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
