# Generated by Django 4.2.2 on 2023-07-05 12:24

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[utils.validators.validate_file_size]),
        ),
    ]
