# Generated by Django 4.2.2 on 2023-07-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_leaverequest_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='leave_balance',
        ),
    ]
