# Generated by Django 4.2.2 on 2023-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_remove_employeedetails_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
    ]
