# Generated by Django 4.2.2 on 2023-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_leavetracker_leave_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
