# Generated by Django 4.2.2 on 2023-07-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_leaverequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='leave_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
