# Generated by Django 4.2.2 on 2023-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_leavetracker_leave_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetracker',
            name='Available_Days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
