# Generated by Django 4.2.2 on 2023-07-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_leavetracker_available_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetracker',
            name='leave_count',
        ),
    ]
