# Generated by Django 4.2.2 on 2023-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_remove_leavetracker_leave_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='Available_Days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
