# Generated by Django 4.2.2 on 2023-08-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_leavetracker_available_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='reports_to',
            new_name='team_lead',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='approval_level',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('LEAD', 'LEAD')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('LEAD', 'LEAD')], max_length=4, null=True),
        ),
    ]
