# Generated by Django 4.2.2 on 2023-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_rename_reports_to_employeedetails_team_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('LEAD', 'LEAD')], default='LEAD', max_length=4, null=True),
        ),
    ]
