# Generated by Django 4.2.2 on 2023-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_alter_leaverequest_current_approval_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='approval_level',
            field=models.CharField(blank=True, choices=[('CDO', 'CDO'), ('LEAD', 'LEAD')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.CharField(blank=True, choices=[('CDO', 'CDO'), ('LEAD', 'LEAD')], default='LEAD', max_length=4, null=True),
        ),
    ]
