# Generated by Django 4.2.2 on 2023-08-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_alter_employeedetails_approval_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='current_approval_level',
            field=models.CharField(blank=True, choices=[('from_lead', 'from_lead'), ('from_cdo', 'from_cdo'), ('approved', 'approved')], default='from_lead', max_length=10, null=True),
        ),
    ]
